---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-install"
      label: "Install"
      solveButton: false
    - name: "02-configuration"
      label: "Configuration"
      solveButton: false
    - name: "03-test"
      label: "Test"
      solveButton: false
    - name: "04-stress"
      label: "Stress"
      solveButton: false
    - name: "05-addanotherhost"
      label: "Addanotherhost"
      solveButton: false

tabs:
  - name: "rhel"
    url: /wetty_rhel/ssh/root
  - name: "rhel2"
    url: /wetty_rhel2/ssh/root
  - name: "rhel3"
    url: /wetty_rhel3/ssh/root
  - name: "rhel4"
    url: /wetty_rhel4/ssh/root
  - name: "Grafana"
    url: https://cockpit-${guid}.${domain}/
