---
virtualmachines:
  - name: "rhel2"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
  - name: "rhel3"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
  - name: "rhel"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    packages:
      - cockpit
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
      - name: grafana
        ports:
          - port: 3000
            protocol: TCP
            targetPort: 3000
            name: grafana
    routes:
      - name: grafana
        host: cockpit
        service: grafana
        targetPort: 3000
        tls: true
        tls_termination: Edge
  - name: "rhel4"
    image: "rhel-10-0-07-09-25-3"
    bootloader: efi
    memory: "4G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "nodes"
    networks:
      - default
